# Generated by Django 2.2.14 on 2020-08-17 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200806_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='stock_no',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
