# Generated by Django 2.2.14 on 2020-08-20 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200819_0844'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='ordered',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='ordered',
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('D', 'Draft'), ('U', 'Unpaid'), ('P', 'Paid'), ('S', 'Shiping'), ('F', 'Finished'), ('C', 'Canceled')], default='D', max_length=1),
        ),
    ]
