# Generated by Django 3.0.8 on 2020-11-22 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20201121_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='large_image_url',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='slug',
            field=models.SlugField(max_length=200),
        ),
    ]
