# Generated by Django 2.2.14 on 2020-12-06 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20201122_1157'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('models_name', models.CharField(choices=[('BoW', 'Bag of Words'), ('tf-idf', 'TF-IDF'), ('idf', 'IDF')], default='tf-idf', max_length=10)),
                ('created', models.DateTimeField(editable=False)),
                ('modified', models.DateTimeField()),
            ],
        ),
    ]
