# Generated by Django 2.2.14 on 2020-12-06 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_recommendation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recommendation',
            name='created',
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
